name: flazy
description: Some common widgets for flutter.
version: 0.0.1
repository: https://github.com/Freonius/flazy.git
homepage: https://github.com/Freonius/flazy

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
